# Generated by Django 5.2.5 on 2025-08-08 02:30

import django.db.models.deletion
import people.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('coordenador', models.CharField(max_length=100, verbose_name='Coordenador')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('carga_horaria', models.PositiveIntegerField(verbose_name='Carga Horária')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_by', models.ForeignKey(null=True, on_delete=models.SET(people.models.get_sentinel_user), related_name='created_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(null=True, on_delete=models.SET(people.models.get_sentinel_user), related_name='updated_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('matricula', models.CharField(max_length=20, unique=True, verbose_name='Matrícula')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('semestre', models.PositiveIntegerField(choices=[(1, '1º Semestre'), (2, '2º Semestre'), (3, '3º Semestre'), (4, '4º Semestre'), (5, '5º Semestre'), (6, '6º Semestre'), (7, '7º Semestre'), (8, '8º Semestre'), (9, '9º Semestre'), (10, '10º Semestre')], default=1, verbose_name='Semestre')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('desvinculado', 'Desvinculado'), ('formado', 'Formado')], default='ativo', max_length=20, verbose_name='Status')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_by', models.ForeignKey(null=True, on_delete=models.SET(people.models.get_sentinel_user), related_name='created_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(null=True, on_delete=models.SET(people.models.get_sentinel_user), related_name='updated_%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='people.curso', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'ordering': ['nome'],
            },
        ),
    ]
